FROM lmsysorg/sglang:dev-cu13

ARG EFA_VERSION=1.47.0

RUN apt-get update && apt-get install -y pciutils environment-modules tcl libnl-3-dev libnl-route-3-dev

RUN cd $HOME \
    && curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${EFA_VERSION}.tar.gz \
    && tar -xf aws-efa-installer-${EFA_VERSION}.tar.gz \
    && cd aws-efa-installer \
    && ./efa_installer.sh -y --skip-kmod --skip-limit-conf --no-verify

ENV PATH=/opt/amazon/efa/bin:/opt/amazon/openmpi/bin:$PATH \
    LD_LIBRARY_PATH=/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:$LD_LIBRARY_PATH \
    FI_PROVIDER=efa \
    FI_EFA_USE_DEVICE_RDMA=1
